name: Build firmware - All Dagoma variants

on:
  pull_request:
    branches:
      - DE200-2.1.x
    paths:
      - '.github/workflows/build_*.yaml'
      - 'Marlin/**'
  push:
    branches:
      - DE200-2.1.x
    paths:
      - '.github/workflows/build_*.yaml'
      - 'Marlin/**'
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build_en:
    strategy:
      fail-fast: false
      matrix:
        lang:
          - en
        screen:     [STD]
        extruder:   [STD, PLUS, BICOLOR]
        zscrews:    [STD, EXPERT]
        size:       [STD, XL]
        warping:    [STD, BED_ATELIER3D]
        thermistor: [WHITE, BLACK]
        pinout:     [STD, MKS]
        head:       [STD, Z122]
        exclude:
          - pinout:   MKS
            extruder: BICOLOR   # Pinout for Extruder 2 not defined in standard MKS_BASE_1.5
    permissions:
      contents: write
    name: "Build: ${{ matrix.lang }}"
    uses: ./.github/workflows/build_single.yaml
    with:
      lang:       ${{ matrix.lang }}
      screen:     ${{ matrix.screen }}
      extruder:   ${{ matrix.extruder }}
      zscrews:    ${{ matrix.zscrews }}
      size:       ${{ matrix.size }}
      warping:    ${{ matrix.warping }}
      thermistor: ${{ matrix.thermistor }}
      pinout:     ${{ matrix.pinout }}
      head:       ${{ matrix.head }}
    secrets: inherit

  build_noscreen:
    strategy:
      fail-fast: false
      matrix:
        lang:
          - en
        screen:     [NONE]
        extruder:   [STD]
        zscrews:    [STD]
        size:       [STD]
        warping:    [STD, BED_ATELIER3D]
        thermistor: [WHITE, BLACK]
        pinout:     [STD]
        head:       [STD]
        exclude:
          - pinout:   MKS
            extruder: BICOLOR   # Pinout for Extruder 2 not defined in standard MKS_BASE_1.5
    permissions:
      contents: write
    name: "Build: ${{ matrix.lang }}"
    uses: ./.github/workflows/build_single.yaml
    with:
      lang:       ${{ matrix.lang }}
      screen:     ${{ matrix.screen }}
      extruder:   ${{ matrix.extruder }}
      zscrews:    ${{ matrix.zscrews }}
      size:       ${{ matrix.size }}
      warping:    ${{ matrix.warping }}
      thermistor: ${{ matrix.thermistor }}
      pinout:     ${{ matrix.pinout }}
      head:       ${{ matrix.head }}
    secrets: inherit

  build_fr:
    needs: build_en
    strategy:
      fail-fast: false
      matrix:
        lang:
          - fr
        screen:     [STD]
        extruder:   [STD, PLUS, BICOLOR]
        zscrews:    [STD, EXPERT]
        size:       [STD, XL]
        warping:    [STD, BED_ATELIER3D]
        thermistor: [WHITE, BLACK]
        pinout:     [STD, MKS]
        head:       [STD, Z122]
        exclude:
          - pinout: MKS
            extruder: BICOLOR   # Pinout for Extruder 2 not defined in standard MKS_BASE_1.5
    permissions:
      contents: write
    name: "Build: ${{ matrix.lang }}"
    uses: ./.github/workflows/build_single.yaml
    with:
      lang:       ${{ matrix.lang }}
      screen:     ${{ matrix.screen }}
      extruder:   ${{ matrix.extruder }}
      zscrews:    ${{ matrix.zscrews }}
      size:       ${{ matrix.size }}
      warping:    ${{ matrix.warping }}
      thermistor: ${{ matrix.thermistor }}
      pinout:     ${{ matrix.pinout }}
      head:       ${{ matrix.head }}
    secrets: inherit

  build_de:
    needs: build_en
    strategy:
      fail-fast: false
      matrix:
        lang:
          - de
        screen:     [STD]
        extruder:   [STD, PLUS, BICOLOR]
        zscrews:    [STD, EXPERT]
        size:       [STD, XL]
        warping:    [STD, BED_ATELIER3D]
        thermistor: [WHITE, BLACK]
        pinout:     [STD, MKS]
        head:       [STD, Z122]
        exclude:
          - pinout:   MKS
            extruder: BICOLOR   # Pinout for Extruder 2 not defined in standard MKS_BASE_1.5
    permissions:
      contents: write
    name: "Build: ${{ matrix.lang }}"
    uses: ./.github/workflows/build_single.yaml
    with:
      lang:       ${{ matrix.lang }}
      screen:     ${{ matrix.screen }}
      extruder:   ${{ matrix.extruder }}
      zscrews:    ${{ matrix.zscrews }}
      size:       ${{ matrix.size }}
      warping:    ${{ matrix.warping }}
      thermistor: ${{ matrix.thermistor }}
      pinout:     ${{ matrix.pinout }}
      head:       ${{ matrix.head }}
    secrets: inherit
