name: Build firmware - Single variant

on:
  workflow_dispatch:
    # Note: We are at the Github maximum of 10 inputs
    inputs:
      lang:
        description: 'Language:'
        options:
            - en
            - an
            - bg
            - ca
            - cz
            - da
            - de
            - el
            - el_CY
            - es
            - eu
            - fi
            - fr
            - gl
            - hr
            - hu
            - it
            - jp_kana
            - ko_KR
            - nl
            - pl
            - pt
            - pt_br
            - ro
            - ru
            - sk
            - sv
            - tr
            - uk
            - vi
            - zh_CN
            - zh_TW
        required: true
        type: choice
        default: 'en'
      screen:
        description: 'Screen (Std, None):'
        options: [Std, None]
        required: true
        type: choice
        default: Std
      extruder:
        description: 'extruder (Std, Extruder+, Bicolor):'
        options: [Std, Extruder+, Bicolor]
        required: true
        type: choice
        default: Std
      zscrews:
        description: 'Z-Screws (Std, Expert Pack):'
        options: [Std, Expert]
        required: true
        type: choice
        default: Std
      size:
        description: 'Size (Std, XL):'
        options: [Std, xl]
        required: true
        type: choice
        default: Std
      warping:
        description: 'Anti-Warping (Std, Bed):'
        options: [Std, Bed]
        required: true
        type: choice
        default: Std
      thermist:
        description: 'Thermistor type (White, Black):'
        options: [White, Black]
        required: true
        type: choice
        default: White
      pinout:
        description: 'Pinout (Std, MKS):'
        options: [Std, MKS]
        required: true
        type: choice
        default: Std
      head:
        description: 'Print head (Std, Z122):'
        options: [Std, Z122]  # Future Std+BLtouch, Z122+BLtouch
        required: true
        type: choice
        default: Std

  workflow_call:
    inputs:
      lang:
        description: 'Language:'
        required: true
        type: string
      screen:
        description: 'Screen (Std, None):'
        required: true
        type: string
      extruder:
        description: 'extruder (Std, Extruder+, Bicolor):'
        required: true
        type: string
      zscrews:
        description: 'Z-Screws (Std, Expert Pack):'
        required: true
        type: string
      size:
        description: 'Size (Std, XL):'
        required: true
        type: string
      warping:
        description: 'Anti-Warping (Std, Bed):'
        required: true
        type: string
      thermist:
        description: 'Thermistor type (White, Black):'
        required: true
        type: string
      pinout:
        description: 'Pinout (Std, MKS):'
        required: true
        type: string
      head:
        description: 'Print head (Std, Z122):'
        required: true
        type: string

concurrency:
  group: "\
    ${{ github.workflow_ref }}-${{ github.ref }}\
    -lang:${{ inputs.lang }}\
    -screen:${{ inputs.screen }}\
    -extruder:${{ inputs.extruder }}\
    -zscrews:${{ inputs.zscrews }}\
    -size:${{ inputs.size }}\
    -warping:${{ inputs.warping }}\
    -thermistor:${{ inputs.thermist }}\
    -pinout:${{ inputs.pinout }}\
    -head:${{ inputs.head }}\
    "
  cancel-in-progress: true

jobs:
  build:
    env:
      BUILD_FILE: ${{ format('{0}{1}{2}{3}{4}{5}{6}{7}{8}{9}{10}{11}{12}{13}{14}{15}{16}{17}{18}',
        'DE200-2.1.x_',
        (inputs.screen    == 'None'  && 'nolcd') || inputs.lang,
        (inputs.screen    != 'None'  && inputs.screen != 'Std' && '_') || '',
        (inputs.screen    != 'None'  && inputs.screen != 'Std' && inputs.screen) || '',
        (inputs.extruder  != 'Std'   && '_') || '',
        (inputs.extruder  != 'Std'   && inputs.extruder) || '',
        (inputs.zscrews   != 'Std'   && '_') || '',
        (inputs.zscrews   != 'Std'   && inputs.zscrews) || '',
        (inputs.size      != 'Std'   && '_') || '',
        (inputs.size      != 'Std'   && inputs.size) || '',
        (inputs.warping   != 'Std'   && '_') || '',
        (inputs.warping   != 'Std'   && inputs.warping) || '',
        (inputs.thermist  != 'White' && '_') || '',
        (inputs.thermist  != 'White' && inputs.thermist) || '',
        (inputs.pinout    != 'Std'   && '_') || '',
        (inputs.pinout    != 'Std'   && inputs.pinout) || '',
        (inputs.head      != 'Std'   && '_') || '',
        (inputs.head      != 'Std'   && inputs.head) || '',
        '.hex') }}
    name: "Build:
      ${{ (inputs.screen == 'None' && 'nolcd') || inputs.lang }}
      ${{ (inputs.screen != 'None' && inputs.screen != 'Std' && inputs.screen) || '' }},
      extrud:${{ inputs.extruder }},
      screws:${{ inputs.zscrews }},
      size:${{ inputs.size }},
      thermist:${{ inputs.thermist }},
      pinout:${{ inputs.pinout }},
      head:${{ inputs.head }},
      warp:${{ inputs.warping }}
      "
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
          ~/.platformio/.cache
        key: ${{ github.workflow_ref }}
        save-always: true
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Build with PlatformIO
      run: |
        echo 'Build file:' $BUILD_FILE
        platformio run
      env:
        PLATFORMIO_BUILD_FLAGS: "\
          -D DE200_LANGUAGE=${{ inputs.lang }}
          ${{ (inputs.screen   != 'None' && '-D DE200_SCREEN=') || '' }}\
          ${{ (inputs.screen   != 'None' && inputs.screen) || '' }}
          ${{ (inputs.extruder != 'Std' && '-D DE200_EXTRUDER=') || '' }}\
          ${{ (inputs.extruder != 'Std' && inputs.extruder) || '' }}
          ${{ (inputs.zscrews  != 'Std' && '-D DE200_ZSCREWS=') || '' }}\
          ${{ (inputs.zscrews  != 'Std' && inputs.zscrews) || '' }}
          ${{ (inputs.size     != 'Std' && '-D DE200_SIZE=') || '' }}\
          ${{ (inputs.size     != 'Std' && inputs.size) || '' }}
          ${{ (inputs.warping  != 'Std' && '-D DE200_WARPING=') || '' }}\
          ${{ (inputs.warping  != 'Std' && inputs.warping) || '' }}
          ${{ (inputs.thermist != 'White' && '-D DE200_THERMISTOR=') || '' }}\
          ${{ (inputs.thermist != 'White' && inputs.thermist) || '' }}
          ${{ (inputs.pinout   != 'Std' && '-D DE200_PINOUT=') || '' }}\
          ${{ (inputs.pinout   != 'Std' && inputs.pinout) || '' }}
          ${{ (inputs.head     != 'Std' && '-D DE200_HEAD=') || '' }}\
          ${{ (inputs.head     != 'Std' && inputs.head) || '' }}
          "
    - name: Rename file
      run: mv .pio/build/mega2560/firmware.hex .pio/build/mega2560/$BUILD_FILE

    - if: ${{ github.event_name != 'release' }}
      name: Upload artefact
      uses: actions/upload-artifact@v4
      # https://github.com/marketplace/actions/upload-a-build-artifact
      with:
        name: ${{ env.BUILD_FILE }}
        path: .pio/build/mega2560/${{ env.BUILD_FILE }}
        compression-level: 9
        if-no-files-found: error

    - if: ${{ github.event_name == 'release' }}
      name: Upload release
      run: gh release upload ${{github.event.release.tag_name}} .pio/build/mega2560/$BUILD_FILE
      env:
        GITHUB_TOKEN: ${{ github.TOKEN }}
