name: Build firmware - Manual (single variant)

on:
  workflow_dispatch:
    # Note: We are at the Github maximum of 10 inputs
    inputs:
      lang:
        description: 'Language:'
        options:
            - en
            - an
            - bg
            - ca
            - cz
            - da
            - de
            - el
            - el_CY
            - es
            - eu
            - fi
            - fr
            - gl
            - hr
            - hu
            - it
            - jp_kana
            - ko_KR
            - nl
            - pl
            - pt
            - pt_br
            - ro
            - ru
            - sk
            - sv
            - tr
            - uk
            - vi
            - zh_CN
            - zh_TW
        required: true
        type: choice
        default: 'en'
      bicol:
        description: 'Bicolor (0, 1):'
        options: [0, 1]
        required: true
        type: choice
        default: 0
      filsens:
        description: 'Extruder+ (0, 1):'
        options: [0, 1]
        required: true
        type: choice
        default: 0
      trapez:
        description: 'Trapezoidal (0, 1):'
        options: [0, 1]
        required: true
        type: choice
        default: 0
      xl:
        description: 'XL (0, 1):'
        options: [0, 1]
        required: true
        type: choice
        default: 0
      nolcd:
        description: 'No LCD (0, 1):'
        options: [0, 1]
        required: true
        type: choice
        default: 0
      therm:
        description: 'Black thermistor wires (0, 1):'
        options: [0, 1]
        required: true
        type: choice
        default: 0
      bltouch:
        description: 'BLtouch (0, 1):'
        options: [0, 1]
        required: true
        type: choice
        default: 0
      pinout:
        description: 'MKS std pinout (0, 1):'
        options: [0, 1]
        required: true
        type: choice
        default: 0
      z122:
        description: 'Z122 head (0, 1):'
        options: [0, 1]
        required: true
        type: choice
        default: 0

concurrency:
  group: "\
    ${{ github.workflow_ref }}-${{ github.ref }}\
    -lang:${{ inputs.lang }}\
    -bicol:${{ inputs.bicol }}\
    -sens:${{ inputs.filsens }}\
    -trapez:${{ inputs.trapez }}\
    -xl:${{ inputs.xl }}\
    -nolcd:${{ inputs.nolcd }}\
    -blktherm:${{ inputs.therm }}\
    -bltouch:${{ inputs.bltouch }}\
    -pinout:${{ inputs.pinout }}\
    -z122:${{ inputs.z122 }}\
    "
  cancel-in-progress: true

jobs:
  build_multiple:
    runs-on: ubuntu-latest
    name: Build
    uses: ./.github/workflows/build_single.yaml
    with:
      lang:     ${{ inputs.lang }}
      bicol:    ${{ inputs.bicol }}
      filsens:  ${{ inputs.filsens }}
      trapez:   ${{ inputs.trapez }}
      xl:       ${{ inputs.xl }}
      nolcd:    ${{ inputs.nolcd }}
      therm:    ${{ inputs.therm }}
      bltouch:  ${{ inputs.bltouch }}
      pinout:   ${{ inputs.pinout }}
      z122:     ${{ inputs.z122 }}
    secrets: inherit
