name: Build firmware - All Dagoma variants

on:
  pull_request:
    branches:
      - DE200-2.1.x
    paths:
      - '.github/workflows/build_*.yaml'
      - 'Marlin/**'
  push:
    branches:
      - DE200-2.1.x
    paths:
      - '.github/workflows/build_*.yaml'
      - 'Marlin/**'
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build_multiple:
    strategy:
      fail-fast: false
      matrix:
        lang:
          - en
          - fr
          - de
        screen: [Std, None]
        extruder: [Std, Extruder+, Bicolor]
        z_screws: [Std, Expert]
        size: [Std, xl]
        warping: [Std, Bed]
        thermist: [White, Black]
        pinout: [Std]
        head: [Std, Z122]
        exclude:
          - screen: None
            lang: fr            # language is irrelevant without screen
          - screen: None
            lang: de            # language is irrelevant to nolcd
          - screen: None
            extruder: Extruder+ # Filament sensor (and hence filament runout and hence advanced pause) needs lcd
          - screen: None
            extruder: Bicolor  # Filament sensor (and hence filament runout and hence advanced pause) needs lcd
          - pinout: Mks
            extruder: Bicolor  # no pinouts for filament sensor 2 on standard pinouts
    permissions:
      contents: write
    name: Build ${{ matrix.lang }}
    uses: ./.github/workflows/build_single.yaml
    with:
      lang:     ${{ matrix.lang }}
      screen:   ${{ matrix.screen }}
      extruder: ${{ matrix.extruder }}
      z_screws: ${{ matrix.z_screws }}
      size:     ${{ matrix.size }}
      warping:  ${{ matrix.warping }}
      thermist: ${{ matrix.thermist }}
      pinout:   ${{ matrix.pinout }}
      head:     ${{ matrix.head }}
    secrets: inherit
