name: Build firmware - All Dagoma variants

on:
  pull_request:
    branches:
      - DE200-2.1.x
  push:
    branches:
      - DE200-2.1.x
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build_multiple:
    strategy:
      fail-fast: false
      matrix:
        lang:
          - en
          - fr
          - de
        bicol: [0, 1]
        filsens: [0, 1]
        trapez: [0, 1]
        xl: [0, 1]
        nolcd: [0, 1]
        therm: [0, 1]
        pinout: [0]
        z122: [0]
        bltouch: [0]
        exclude:
          - nolcd: 1
            lang: fr
          - nolcd: 1
            lang: de
          - bicol: 1
            filsens: 0 # bicolor implies extruder+
    permissions:
      contents: write
    name: Build ${{ matrix.lang }}
    uses: ./.github/workflows/build_single.yaml
    with:
      lang:     ${{ matrix.lang }}
      bicol:    ${{ matrix.bicol }}
      filsens:  ${{ matrix.filsens }}
      trapez:   ${{ matrix.trapez }}
      xl:       ${{ matrix.xl }}
      nolcd:    ${{ matrix.nolcd }}
      therm:    ${{ matrix.therm }}
      pinout:   ${{ matrix.pinout }}
      z122:     ${{ matrix.z122 }}
      bltouch:  ${{ matrix.bltouch }}
    secrets: inherit
