name: Build firmware - Release

on:
  release:
    types:
      - published
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_multiple:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        lang:
          - en
          - fr
          - de
        bicol: [0, 1]
        filsens: [0, 1]
        trapez: [0, 1]
        xl: [0, 1]
        nolcd: [0, 1]
        therm: [0, 1]
        bltouch: [0]
        pinout: [0]
        z122: [0]
        exclude:
          - nolcd: 1
            lang: [fr, de]
    name: Build ${{ matrix.lang }}
    uses: Sophist-UK/Marlin-DiscoEasy200/.github/workflows/build_single.yaml@DE200-2.1.x
    with:
      lang:     ${{ matrix.lang }}
      bicol:    ${{ matrix.bicol }}
      filsens:  ${{ matrix.filsens }}
      trapez:   ${{ matrix.trap }}
      xl:       ${{ matrix.xl }}
      nolcd:    ${{ matrix.nolcd }}
      therm:    ${{ matrix.therm }}
      bltouch:  ${{ matrix.bltouch }}
      pinout:   ${{ matrix.pinout }}
      z122:     ${{ matrix.z122 }}
    secrets: inherit
